const express=require("express");
const crypto=require("crypto");
const catalog=require("./catalog.json");
const app=express();
const UA="Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like Mac OS X) AppleWebKit/605.1.15 Version/18.5 Mobile/15E148 Safari/604.1";
const KEY=Buffer.from("C5D58EF67A7584E4A29F6C35BBC4EB12","hex");
const DISCOVERY=["https://media.savetube.vip/api/random-cdn","https://media.savetube.me/api/random-cdn"];
const cache=new Map(), inFlight=new Map(), autoState=new Map();
app.use((req,res,next)=>{res.set("Access-Control-Allow-Origin","*");console.log("[REQ]",req.method,req.originalUrl);next()});
const metas=catalog.map(x=>({id:"khoai_"+x.videoId,type:"movie",name:x.title,poster:"https://i.ytimg.com/vi/"+x.videoId+"/hqdefault.jpg",posterShape:"landscape",background:"https://i.ytimg.com/vi/"+x.videoId+"/maxresdefault.jpg",description:"Khoai Lang Thang / Food & Travel",runtime:x.duration?Math.round(x.duration/60)+" min":undefined}));
const byId=new Map(metas.map(x=>[x.id,x]));
const manifest={id:"vn.ivyplay.youtube.khoailangthang",version:"3.3.0",name:"Khoai Lang Thang YouTube",description:"Direct CDN playback: Render resolves then redirects; media does not proxy through Render.",resources:["catalog",{name:"meta",types:["movie"],idPrefixes:["khoai_"]},{name:"stream",types:["movie"],idPrefixes:["khoai_"]}],types:["movie"],idPrefixes:["khoai_"],catalogs:[{type:"movie",id:"khoai-lang-thang",name:"Khoai Lang Thang"}],behaviorHints:{adult:false,p2pNotSupported:true}};
function timeout(ms){return AbortSignal.timeout(ms)}
function decrypt(enc){const raw=Buffer.from(String(enc).replace(/\s/g,""),"base64"),iv=raw.subarray(0,16);const d=crypto.createDecipheriv("aes-128-cbc",KEY,iv);return JSON.parse(Buffer.concat([d.update(raw.subarray(16)),d.final()]).toString("utf8"))}
async function cdn(){for(const ep of DISCOVERY){try{const r=await fetch(ep,{headers:{"User-Agent":UA,Accept:"application/json",Origin:"https://yt.savetube.me",Referer:"https://yt.savetube.me/"},signal:timeout(5000)});const j=await r.json();if(r.ok&&j?.cdn)return j.cdn}catch(e){console.log("[CDN-MISS]",ep,String(e))}}throw Error("No SaveTube CDN")}
async function context(id){const c=await cdn(),base="https://"+c,h={"Content-Type":"application/json",Accept:"application/json","User-Agent":UA,Origin:"https://yt.savetube.me",Referer:"https://yt.savetube.me/"};const r=await fetch(base+"/v2/info",{method:"POST",headers:h,body:JSON.stringify({url:"https://www.youtube.com/watch?v="+id}),signal:timeout(12000)});const j=await r.json();if(!r.ok||!j?.data)throw Error("SaveTube info "+r.status);return{base,h,info:decrypt(j.data),cdn:c}}
async function resolveQuality(id,q){const key=id+":"+q,hit=cache.get(key);if(hit&&hit.expires>Date.now())return hit;if(inFlight.has(key))return inFlight.get(key);const p=(async()=>{const c=await context(id);const r=await fetch(c.base+"/download",{method:"POST",headers:c.h,body:JSON.stringify({id,downloadType:"video",quality:q,key:c.info.key}),signal:timeout(12000)});const t=await r.text();let j;try{j=JSON.parse(t)}catch{}const data=j?.data||{};const url=data.downloadUrl||data.url||j?.downloadUrl;if(!r.ok||!url)throw Error("SaveTube download "+r.status);const reported=String(data.quality||data.resolution||data.height||q).replace(/p$/i,"");const v={url,quality:q,reportedQuality:reported,cdn:c.cdn,expires:Date.now()+90*60*1000};cache.set(key,v);console.log("[RESOLVED]",id,"requested="+q+"p","reported="+reported+"p",c.cdn);return v})().finally(()=>inFlight.delete(key));inFlight.set(key,p);return p}
async function resolveAuto(id){const qs=id==="B1qT38bVsXc"?["2160","1440","1080","720","480","360"]:["720","360"];let st=autoState.get(id)||{idx:0,last:0};const start=Math.min(st.idx,qs.length-1);for(let i=start;i<qs.length;i++){const q=qs[i];try{const x=await resolveQuality(id,q);autoState.set(id,{idx:i,last:Date.now()});return x}catch(e){console.log("[QUALITY-MISS]",id,q+"p",e.message)}}throw Error("No playable SaveTube URL")}
function downgradeAuto(id){const qs=id==="B1qT38bVsXc"?["2160","1440","1080","720","480","360"]:["720","360"];const st=autoState.get(id)||{idx:0,last:Date.now()};const next=Math.min(st.idx+1,qs.length-1);autoState.set(id,{idx:next,last:Date.now()});console.log("[AUTO-DOWNGRADE]",id,qs[st.idx]||qs[0],"->",qs[next]);return qs[next]}
app.get("/",(_,r)=>r.json({ok:true,name:manifest.name,version:manifest.version,videos:metas.length,cache:cache.size}));
app.get("/manifest.json",(_,r)=>r.json(manifest));
app.get("/player",(_,r)=>r.sendFile("player.html",{root:__dirname}));
app.get("/play/:id/:quality.mp4",async(q,r)=>{try{const quality=String(q.params.quality);if(!["2160","1440","1080","720","480","360"].includes(quality))return r.status(400).json({error:"Unsupported quality"});const x=await resolveQuality(q.params.id,quality);console.log("[DIRECT-PLAY]",q.params.id,"requested="+x.quality+"p","reported="+x.reportedQuality+"p",x.cdn);r.set({"Cache-Control":"no-store","Access-Control-Allow-Origin":"*","Location":x.url});r.status(302).end()}catch(e){console.error("[DIRECT-PLAY-FAIL]",q.params.id,e.message);r.status(502).json({error:e.message})}});
app.get("/catalog/movie/khoai-lang-thang.json",(_,r)=>r.json({metas}));
app.get("/catalog/movie/khoai-lang-thang/:extra.json",(_,r)=>r.json({metas}));
app.get("/meta/movie/:id.json",(q,r)=>{const m=byId.get(q.params.id);return m?r.json({meta:m}):r.status(404).json({meta:null})});
app.get("/stream/movie/:id.json",(q,r)=>{const id=q.params.id.startsWith("khoai_")?q.params.id.slice(6):"";return id?r.json({streams:[{name:"YouTube • AUTO",title:"AUTO fallback on player retry",url:`${q.protocol}://${q.get("host")}/play/${id}/auto.mp4`,behaviorHints:{notWebReady:true}}]}):r.json({streams:[]})});
app.get("/inspect/:id",async(q,r)=>{try{const c=await context(q.params.id);const i=c.info||{};const formats=i.video_formats||i.videoFormats||i.formats||[];const safe=formats.map(f=>({height:f.height,quality:f.quality,label:f.label,mimeType:f.mimeType||f.mime_type,type:f.type,ext:f.ext,hasUrl:!!f.url}));const keys=Object.keys(i).filter(k=>/hls|dash|manifest|format|quality/i.test(k));const manifests={};for(const k of keys){if(/hls|dash|manifest/i.test(k))manifests[k]=typeof i[k]==="string"?i[k].slice(0,120):i[k]}console.log("[INSPECT]",q.params.id,"keys="+keys.join(","),"formats="+safe.length,"manifests="+Object.keys(manifests).join(","));r.json({videoId:q.params.id,keys,formats:safe,manifests})}catch(e){console.error("[INSPECT-FAIL]",q.params.id,e.message);r.status(502).json({error:e.message})}});
app.get("/resolve/:id",async(q,r)=>{try{const x=await resolveAuto(q.params.id);r.set("Cache-Control","no-store");r.json({videoId:q.params.id,requestedQuality:x.quality,reportedQuality:x.reportedQuality,url:x.url,cdn:x.cdn})}catch(e){console.error("[RESOLVE-FAIL]",q.params.id,e.message);r.status(502).json({error:e.message})}});
app.get("/play/:id/auto.mp4",async(q,r)=>{try{const id=q.params.id;const x=await resolveQuality(id,id==="B1qT38bVsXc"?"1440":"720");console.log("[PLAY-REDIRECT-STABLE]",id,"requested="+x.quality+"p","reported="+x.reportedQuality+"p",x.cdn);r.set({"Cache-Control":"no-store","Access-Control-Allow-Origin":"*","Location":x.url});r.status(302).end()}catch(e){console.error("[PLAY-FAIL]",q.params.id,e.message);r.status(502).json({error:e.message})}});
app.listen(process.env.PORT||3000,"0.0.0.0",()=>{console.log("Khoai addon",manifest.version,"videos",metas.length);setTimeout(async()=>{try{const x=await resolveAuto("B1qT38bVsXc");console.log("[SELFTEST] SaveTube OK","requested="+x.quality+"p","reported="+x.reportedQuality+"p",x.cdn)}catch(e){console.error("[SELFTEST] SaveTube FAILED",e.message)}},1500)});
